### ISSUE TITLE
scn export:The exported scns are not directly usable in app right now as we need to add a cors url at start of every starturl in order to make the exported scns work in webaverse.

### ISSUE THREAD

**Issue by DavinciDreams** [TheNexusCity/editaverse#17]
Scn import:
Right now the native scn import seems to be working only for 3d models only. As there is no support of apps such as sword, pets, pistol, vehicle, atmospheric sky. We are unable to import whole scenes into editaverse due to limitation of support for .metaversefiles. Otherwise, if we bring in scenes that don't include .metaversefiles in apps(only include 3d models), they work fine.

**Comment by 0reo** [comment]
is this replacing #2 ?
