### ISSUE TITLE
Metamask Login Doesn't works

### ISSUE THREAD

**Issue by kinjalravel** [TheNexusCity/editaverse#24]
![image](https://user-images.githubusercontent.com/41296632/168527378-c9d8d9b8-0d1c-40ab-8d74-6d3b341d9314.png)

**Comment by rakeshghasadiya** [comment]
https://user-images.githubusercontent.com/12234177/168628730-10b2c1d2-b830-4294-80a3-65777ca9fdf8.mp4

**Comment by kinjalravel** [comment]
@alisaad673 well address is just added so in future we want to link multiple login methods together then it would be possible - for example you login with Metamask first and after that you will get an option to login with Discord and  after successful login it would be link together
