### ISSUE TITLE
Email login doesn't works

### ISSUE THREAD

**Issue by kinjalravel** [TheNexusCity/editaverse#25]
![image](https://user-images.githubusercontent.com/41296632/168527509-14bfe43b-4d83-45fd-8be6-7986f447086d.png)

**Comment by rakeshghasadiya** [comment]
https://user-images.githubusercontent.com/12234177/168628510-817d39d3-68d7-41ea-b6b3-4742485dd56e.mp4

**Comment by kinjalravel** [comment]
@alisaad673 Thank you for confirmation - I am closing this issue for now
