### ISSUE TITLE
login with email

### ISSUE THREAD

**Issue by DavinciDreams** [TheNexusCity/editaverse#37]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/27410147?key=e9fc4b2a4e01c18157a812eb141c3de7&size=orig) 

---
**Source URL**:
[https://editaverse.n3xus.city/projects/new](https://editaverse.n3xus.city/projects/new)

**Comment by DavinciDreams** [comment]
there is no enter or confirm button for login with email. Discord login takes me to discord authorization, but doesn't seem to update in app.

**Comment by kinjalravel** [comment]
@DavinciDreams it's working actually - you need to add your email into the email text box and then need to press on Login with email and it will send you OTP though email that you can use to login 

Currently only approved email address are allowed to send email ( I will need to add you to AWS SES list if you want to try this feature)

Closing in favour  of #25
